document.addEventListener('DOMContentLoaded', function (){
let cart = document.getElementById("prod");
let imageData = [
{
    id: "ft-1",
    name: "apples",
    img: ("../src/images/apples.jpeg"),
    alt:"apple"
},
{
    id: "ft-2",
    name: "grover",
    price: "30.99",
    img: ("../src/images/grover.jpg"),
    alt:"grover",
},
{
    id: "ft-3",
    name: "cherry",
    price: "35.99",
    img: ("../src/images/cherry.jpg"),
    alt: "cherry",
},
{
    id: "ft-4", 
    name: "pawpaw",
    price: "40.99",
    img: ("../src/images/pawpaw.jpg"),
    alt:"pawpaw",
}
];
let generateHeader = ()=>{
    return (cart.innerHTML = imageData.map((k)=>{
        let { id, name, price, img, alt } = k; 
        return`
        
          <img src="${img}" alt="${alt}" class="img-fluid">
          <div class="cart-des">
              <div class="prd-title">${name}</div>
              <div class="prd-price">${price}</div>
              <div class="prod-btn">
                <i class="bi bi-dash" id=${id}></i>
                <div id=${id} class="prod-quantity">0</div>
                <i  class="bi bi-plus" id=${id}></i>
              </div>
          </div>
          <i class="bi bi-trash3-fill remove-item"></i>
        
        
        `
    }));
}; generateHeader();
});

// let decrement = document.querySelectorAll(".bi-plus");
// let increment = document.querySelectorAll(".bi-dash");
// let update = document.querySelector(".prod-quantity");

// decrement.addEventListener("click", function (id) {
    
//     console.log(id);
// });

// increment.addEventListener("click", function (id) {
    
//     console.log(id);
// });


// let increment = ()=>{
//     console.log("increment");
// };
// let update = ()=>{

// };
/*
// let items = [
//     {
//         id: "ft-1",
//         name: "apples",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/apples.jpeg"),
//         alt:"apple"
//     },
//     {
//         id: "ft-2",
//         name: "grover",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/grover.jpg"),
//         alt:"grover",
//     },
//     {
//         id: "ft-3",
//         name: "cherry",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/cherry.jpg"),
//         alt: "cherry",
//     },
//     {
//         id: "ft-4", 
//         name: "pawpaw",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/pawpaw.jpg"),
//         alt:"pawpaw",
//     },
//     {
//         id: "ft-5",
//         name: "apple",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/apple.jpeg"),
//         alt:"apple",
//     },
//     {
//         id: "ft-6",
//         name: "pear",
//         star1: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/pear.jpg"),
//         alt:"pear",
//     },
//     {
//         id: "ft-7",
//         name: "peach",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/peach.jpg"),
//         alt: "peach",
//     },
//     {
//         id: "ft-8", 
//         name: "strawberry",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/berry2.jpg"),
//         alt:"strawberry",
//     },
//     {
//         id: "ft-9",
//         name: "grapes",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/grapes.jpeg"),
//         alt:"grapes",
//     },
//     {
//         id: "ft-10",
//         name: "melon",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images//melon.jpeg"),
//         alt:"melon",
//     },
//     {
//         id: "ft-11",
//         name: "lemon",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/lemon.jpg"),
//         alt: "lemon",
//     },
//     {
//         id: "ft-12", 
//         name: "mangoes",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/mangoes2.webp"),
//         alt:"mangoes",
//     },
//     {
//         id: "ft-13",
//         name: "pomegranate",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/pom.jpg"),
//         alt:"pomegranate",
//     },
//     {
//         id: "ft-14",
//         name: "banana",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images//bananas.jpeg"),
//         alt:"banana",
//     },
//     {
//         id: "ft-15",
//         name: "pine",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/pine.jpeg"),
//         alt: "pine",
//     },
//     {
//         id: "ft-16", 
//         name: "oranges",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/oranges2.jpeg"),
//         alt:"oranges",
//     },
//     {
//         id: "vg-1",
//         name: "cucumber",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/bam.jpeg"),
//         alt:"cucumber"
//     },
//     {
//         id: "vg-2",
//         name: "ginger",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/ginger.jpeg"),
//         alt:"ginger",
//     },
//     {
//         id: "vg-3",
//         name: "chilly",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/illy.jpeg"),
//         alt: "chilly",
//     },
//     {
//         id: "vg-4", 
//         name: "onions",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/onion.webp"),
//         alt:"onions",
//     },
//     {
//         id: "vg-5",
//         name: "mushroom",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/room.jpeg"),
//         alt:"mushroom",
//     },
//     {
//         id: "vg-6",
//         name: "carrot",
//         star1: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/rot.jpeg"),
//         alt:"carrot",
//     },
//     {
//         id: "vg-7",
//         name: "chilly",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/ily.jpg"),
//         alt: "chilly",
//     },
//     {
//         id: "vg-8", 
//         name: "tomatoes",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/mato.jpg"),
//         alt:"tomatoes",
//     },
//     {
//         id: "vg-9",
//         name: "green beans",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/g-beans.jpg"),
//         alt:"green beans",
//     },
//     {
//         id: "vg-10",
//         name: "pumpkin",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/poku.jpg"),
//         alt:"pumpkin",
//     },
//     {
//         id: "vg-11",
//         name: "corn",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/corn.jpg"),
//         alt: "corn",
//     },
//     {
//         id: "vg-12", 
//         name: "egg plant",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/egg-plant.jpg"),
//         alt:"egg plant",
//     },
//     {
//         id: "vg-13",
//         name: "broccoli",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/broccoli.jpg"),
//         alt:"broccoli",
//     },
//     {
//         id: "vg-14",
//         name: "paprika",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/paprika.jpg"),
//         alt:"paprika",
//     },
//     {
//         id: "vg-15",
//         name: "lettuce",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/lettuce.jpg"),
//         alt: "lettuce",
//     },
//     {
//         id: "vg-16", 
//         name: "lemon",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/lemon.jpg"),
//         alt:"lemon",
//     },
//     {
//         id: "mt-1",
//         name: "lobster",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/lobster.jpg"),
//         alt:"lobster"
//     },
//     {
//         id: "mt-2",
//         name: "pork",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/pork.jpg"),
//         alt:"pork",
//     },
//     {
//         id: "mt-3",
//         name: "catfish",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/catfish.jpg"),
//         alt: "catfish",
//     },
//     {
//         id: "mt-4", 
//         name: "chicken",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/chicken.jpg"),
//         alt:"chicken",
//     },
//     {
//         id: "mt-5",
//         name: "beef",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/beef.jpeg"),
//         alt:"beef",
//     },
//     {
//         id: "mt-6",
//         name: "mutton",
//         star1: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/mutton.jpg"),
//         alt:"mutton",
//     },
//     {
//         id: "mt-7",
//         name: "shrimps",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/shrimps.jpg"),
//         alt: "shrimps",
//     },
//     {
//         id: "mt-8", 
//         name: "turkey",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/turkey.jpg"),
//         alt:"turkey",
//     },
//     {
//         id: "mt-9",
//         name: "oyster",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/oyster.jpg"),
//         alt:"oyster",
//     },
//     {
//         id: "mt-10",
//         name: "mackerel",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/mackerel.jpg"),
//         alt:"mackerel",
//     },
//     {
//         id: "mt-11",
//         name: "snail",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/snail.jpg"),
//         alt: "snail",
//     },
//     {
//         id: "mt-12", 
//         name: "crabs",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/crabs.jpg"),
//         alt:"crabs",
//     },
//     {
//         id: "mt-13",
//         name: "star fish",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/star-fish.jpg"),
//         alt:"star fish",
//     },
//     {
//         id: "mt-14",
//         name: "lobster",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/lobster.jpg"),
//         alt:"lobster",
//     },
//     {
//         id: "mt-15",
//         name: "ray",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/ray.jpg"),
//         alt: "ray",
//     },
//     {
//         id: "mt-16", 
//         name: "clown",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/clown.jpg"),
//         alt:"clown",
//     },
//     {
//         id: "dy-1",
//         name: "milk",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/milk.webp"),
//         alt:"milk"
//     },
//     {
//         id: "dy-2",
//         name: "cheese",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/cheese.webp"),
//         alt:"cheese",
//     },
//     {
//         id: "dy-3",
//         name: "curd",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/curd.jpg"),
//         alt: "curd",
//     },
//     {
//         id: "dy-4", 
//         name: "kefir",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/kefir.jpg"),
//         alt:"kefir",
//     },
//     {
//         id: "dy-5",
//         name: "yougurt",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/yug.jpg"),
//         alt:"yougurt",
//     },
//     {
//         id: "dy-6",
//         name: "ghee",
//         star1: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/ghee.jpg"),
//         alt:"ghee",
//     },
//     {
//         id: "dy-7",
//         name: "magarine",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/mag.jpg"),
//         alt: "magarine",
//     },
//     {
//         id: "dy-8", 
//         name: "eggs",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/eggs.jpeg"),
//         alt:"eggs",
//     },
//     {
//         id: "dy-9",
//         name: "sour milk",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/sour.jpeg"),
//         alt:"sour milk",
//     },
//     {
//         id: "dy-10",
//         name: "butter",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/butter.jpg"),
//         alt:"butter",
//     },
//     {
//         id: "dy-11",
//         name: "feta",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/feta.jpg"),
//         alt: "feta",
//     },
//     {
//         id: "dy-12", 
//         name: "pudding",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/pudding.jpg"),
//         alt:"pudding",
//     },
//     {
//         id: "dy-13",
//         name: "condensed milk",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "25.99",
//         img: require("../images/condensed.jpg"),
//         alt:"condensed milk",
//     },
//     {
//         id: "dy-14",
//         name: "quark",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "30.99",
//         img: require("../images/quark.jpg"),
//         alt:"quark",
//     },
//     {
//         id: "dy-15",
//         name: "sherbet",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star-fill",
//         star5: "bi bi-star",
//         price: "35.99",
//         img: require("../images/sherbet.jpg"),
//         alt: "sherbet",
//     },
//     {
//         id: "dy-16", 
//         name: "powerdered milk",
//         star1: "bi bi-star-fill",
//         star2: "bi bi-star-fill",
//         star3: "bi bi-star-fill",
//         star4: "bi bi-star",
//         star5: "bi bi-star",
//         price: "40.99",
//         img: require("../images/kefir.jpg"),
//         alt:"powerdered milk",
//     }
    
    
//     ];
*/











